default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: food_truck_dev

test:
  <<: *default
  database: food_truck_test

production:
  <<: *default
  database: food_truck
